service:
  name: project-backend
  app: project-utils
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  projectGetAll:
    handler: src/lambda/handlers/project.getAll
    events:
      - http:
          method: get
          path: project
  projectCreate:
    handler: src/lambda/handlers/project.create
    events:
      - http:
          method: post
          path: project
  projectSave:
    handler: src/lambda/handlers/project.save
    events:
      - http:
          method: patch
          path: project
  projectGetWithId:
    handler: src/lambda/handlers/project.getWithId
    events:
      - http:
          method: get
          path: project/{id}

  timeSheetGetAll:
    handler: src/lambda/handlers/project.getAll
    events:
      - http:
          method: get
          path: timesheet
  timeSheetGetWithProjectId:
    handler: src/lambda/handlers/time-sheet.getWithProjectId
    events:
      - http:
          method: get
          path: timesheet/project/{id}
  timeSheetGetWithId:
    handler: src/lambda/handlers/time-sheet.getWithId
    events:
      - http:
          method: get
          path: timesheet/{id}
  timeSheetCreate:
    handler: src/lambda/handlers/time-sheet.create
    events:
        - http:
            method: post
            path: timesheet
  timeSheetSave:
    handler: src/lambda/handlers/time-sheet.save
    events:
      - http:
          method: patch
          path: timesheet
